# Generated by Django 4.1.7 on 2023-03-06 18:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cargo", "0001_initial"),
        ("transport", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Transactions",
            new_name="Transaction",
        ),
    ]
